//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  sponsors: Sponsors;
  sponsorsConnection: SponsorsConnection;
  tournament: Tournament;
  tournamentConnection: TournamentConnection;
  contacts: Contacts;
  contactsConnection: ContactsConnection;
  sponsor_benefits: Sponsor_Benefits;
  sponsor_benefitsConnection: Sponsor_BenefitsConnection;
  get_involved: Get_Involved;
  get_involvedConnection: Get_InvolvedConnection;
  site: Site;
  siteConnection: SiteConnection;
  about: About;
  aboutConnection: AboutConnection;
  grants: Grants;
  grantsConnection: GrantsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySponsorsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySponsorsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SponsorsFilter>;
};


export type QueryTournamentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTournamentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TournamentFilter>;
};


export type QueryContactsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactsFilter>;
};


export type QuerySponsor_BenefitsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySponsor_BenefitsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Sponsor_BenefitsFilter>;
};


export type QueryGet_InvolvedArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGet_InvolvedConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Get_InvolvedFilter>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryGrantsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGrantsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GrantsFilter>;
};

export type DocumentFilter = {
  sponsors?: InputMaybe<SponsorsFilter>;
  tournament?: InputMaybe<TournamentFilter>;
  contacts?: InputMaybe<ContactsFilter>;
  sponsor_benefits?: InputMaybe<Sponsor_BenefitsFilter>;
  get_involved?: InputMaybe<Get_InvolvedFilter>;
  site?: InputMaybe<SiteFilter>;
  about?: InputMaybe<AboutFilter>;
  grants?: InputMaybe<GrantsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Sponsors | Tournament | Contacts | Sponsor_Benefits | Get_Involved | Site | About | Grants | Folder;

export type SponsorsItems = {
  __typename?: 'SponsorsItems';
  name: Scalars['String']['output'];
  logo: Scalars['String']['output'];
  alt: Scalars['String']['output'];
  enabled?: Maybe<Scalars['Boolean']['output']>;
};

export type Sponsors = Node & Document & {
  __typename?: 'Sponsors';
  items?: Maybe<Array<Maybe<SponsorsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SponsorsItemsFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  enabled?: InputMaybe<BooleanFilter>;
};

export type SponsorsFilter = {
  items?: InputMaybe<SponsorsItemsFilter>;
};

export type SponsorsConnectionEdges = {
  __typename?: 'SponsorsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sponsors>;
};

export type SponsorsConnection = Connection & {
  __typename?: 'SponsorsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SponsorsConnectionEdges>>>;
};

export type Tournament = Node & Document & {
  __typename?: 'Tournament';
  edition: Scalars['String']['output'];
  date: Scalars['String']['output'];
  time: Scalars['String']['output'];
  venue: Scalars['String']['output'];
  address: Scalars['String']['output'];
  price_player: Scalars['Float']['output'];
  price_foursome: Scalars['Float']['output'];
  holes: Scalars['Float']['output'];
  format: Scalars['String']['output'];
  format_label: Scalars['String']['output'];
  inclusions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  add_ons?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  auction_description?: Maybe<Scalars['String']['output']>;
  section_headline: Scalars['String']['output'];
  section_intro?: Maybe<Scalars['String']['output']>;
  course_description?: Maybe<Scalars['String']['output']>;
  register_headline: Scalars['String']['output'];
  register_intro?: Maybe<Scalars['String']['output']>;
  arrive_by: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TournamentFilter = {
  edition?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  time?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  price_player?: InputMaybe<NumberFilter>;
  price_foursome?: InputMaybe<NumberFilter>;
  holes?: InputMaybe<NumberFilter>;
  format?: InputMaybe<StringFilter>;
  format_label?: InputMaybe<StringFilter>;
  inclusions?: InputMaybe<StringFilter>;
  add_ons?: InputMaybe<StringFilter>;
  auction_description?: InputMaybe<StringFilter>;
  section_headline?: InputMaybe<StringFilter>;
  section_intro?: InputMaybe<StringFilter>;
  course_description?: InputMaybe<StringFilter>;
  register_headline?: InputMaybe<StringFilter>;
  register_intro?: InputMaybe<StringFilter>;
  arrive_by?: InputMaybe<StringFilter>;
};

export type TournamentConnectionEdges = {
  __typename?: 'TournamentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tournament>;
};

export type TournamentConnection = Connection & {
  __typename?: 'TournamentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TournamentConnectionEdges>>>;
};

export type ContactsPlayers = {
  __typename?: 'ContactsPlayers';
  name: Scalars['String']['output'];
  email: Scalars['String']['output'];
};

export type ContactsSponsorship = {
  __typename?: 'ContactsSponsorship';
  name: Scalars['String']['output'];
  email: Scalars['String']['output'];
};

export type Contacts = Node & Document & {
  __typename?: 'Contacts';
  players?: Maybe<ContactsPlayers>;
  sponsorship?: Maybe<Array<Maybe<ContactsSponsorship>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactsPlayersFilter = {
  name?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type ContactsSponsorshipFilter = {
  name?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type ContactsFilter = {
  players?: InputMaybe<ContactsPlayersFilter>;
  sponsorship?: InputMaybe<ContactsSponsorshipFilter>;
};

export type ContactsConnectionEdges = {
  __typename?: 'ContactsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contacts>;
};

export type ContactsConnection = Connection & {
  __typename?: 'ContactsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactsConnectionEdges>>>;
};

export type Sponsor_Benefits = Node & Document & {
  __typename?: 'Sponsor_benefits';
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Sponsor_BenefitsFilter = {
  items?: InputMaybe<StringFilter>;
};

export type Sponsor_BenefitsConnectionEdges = {
  __typename?: 'Sponsor_benefitsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sponsor_Benefits>;
};

export type Sponsor_BenefitsConnection = Connection & {
  __typename?: 'Sponsor_benefitsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Sponsor_BenefitsConnectionEdges>>>;
};

export type Get_InvolvedItems = {
  __typename?: 'Get_involvedItems';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  link_label?: Maybe<Scalars['String']['output']>;
  form?: Maybe<Scalars['String']['output']>;
  form_title?: Maybe<Scalars['String']['output']>;
  coming_soon?: Maybe<Scalars['Boolean']['output']>;
};

export type Get_Involved = Node & Document & {
  __typename?: 'Get_involved';
  items?: Maybe<Array<Maybe<Get_InvolvedItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Get_InvolvedItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link_label?: InputMaybe<StringFilter>;
  form?: InputMaybe<StringFilter>;
  form_title?: InputMaybe<StringFilter>;
  coming_soon?: InputMaybe<BooleanFilter>;
};

export type Get_InvolvedFilter = {
  items?: InputMaybe<Get_InvolvedItemsFilter>;
};

export type Get_InvolvedConnectionEdges = {
  __typename?: 'Get_involvedConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Get_Involved>;
};

export type Get_InvolvedConnection = Connection & {
  __typename?: 'Get_involvedConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Get_InvolvedConnectionEdges>>>;
};

export type SiteSocial = {
  __typename?: 'SiteSocial';
  facebook?: Maybe<Scalars['String']['output']>;
};

export type SiteHero_Mission = {
  __typename?: 'SiteHero_mission';
  badge?: Maybe<Scalars['String']['output']>;
  headline_line1?: Maybe<Scalars['String']['output']>;
  headline_line2?: Maybe<Scalars['String']['output']>;
  headline_accent?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type SiteDonate = {
  __typename?: 'SiteDonate';
  headline?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type SiteSponsor_Cta = {
  __typename?: 'SiteSponsor_cta';
  headline_line1?: Maybe<Scalars['String']['output']>;
  headline_line2?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  copyright: Scalars['String']['output'];
  social?: Maybe<SiteSocial>;
  hero_mission?: Maybe<SiteHero_Mission>;
  donate?: Maybe<SiteDonate>;
  sponsor_cta?: Maybe<SiteSponsor_Cta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSocialFilter = {
  facebook?: InputMaybe<StringFilter>;
};

export type SiteHero_MissionFilter = {
  badge?: InputMaybe<StringFilter>;
  headline_line1?: InputMaybe<StringFilter>;
  headline_line2?: InputMaybe<StringFilter>;
  headline_accent?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type SiteDonateFilter = {
  headline?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type SiteSponsor_CtaFilter = {
  headline_line1?: InputMaybe<StringFilter>;
  headline_line2?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  copyright?: InputMaybe<StringFilter>;
  social?: InputMaybe<SiteSocialFilter>;
  hero_mission?: InputMaybe<SiteHero_MissionFilter>;
  donate?: InputMaybe<SiteDonateFilter>;
  sponsor_cta?: InputMaybe<SiteSponsor_CtaFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AboutFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Grants = Node & Document & {
  __typename?: 'Grants';
  audience: Scalars['String']['output'];
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  cta_label: Scalars['String']['output'];
  form: Scalars['String']['output'];
  theme?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GrantsFilter = {
  audience?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  cta_label?: InputMaybe<StringFilter>;
  form?: InputMaybe<StringFilter>;
  theme?: InputMaybe<StringFilter>;
};

export type GrantsConnectionEdges = {
  __typename?: 'GrantsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Grants>;
};

export type GrantsConnection = Connection & {
  __typename?: 'GrantsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GrantsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSponsors: Sponsors;
  createSponsors: Sponsors;
  updateTournament: Tournament;
  createTournament: Tournament;
  updateContacts: Contacts;
  createContacts: Contacts;
  updateSponsor_benefits: Sponsor_Benefits;
  createSponsor_benefits: Sponsor_Benefits;
  updateGet_involved: Get_Involved;
  createGet_involved: Get_Involved;
  updateSite: Site;
  createSite: Site;
  updateAbout: About;
  createAbout: About;
  updateGrants: Grants;
  createGrants: Grants;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSponsorsArgs = {
  relativePath: Scalars['String']['input'];
  params: SponsorsMutation;
};


export type MutationCreateSponsorsArgs = {
  relativePath: Scalars['String']['input'];
  params: SponsorsMutation;
};


export type MutationUpdateTournamentArgs = {
  relativePath: Scalars['String']['input'];
  params: TournamentMutation;
};


export type MutationCreateTournamentArgs = {
  relativePath: Scalars['String']['input'];
  params: TournamentMutation;
};


export type MutationUpdateContactsArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactsMutation;
};


export type MutationCreateContactsArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactsMutation;
};


export type MutationUpdateSponsor_BenefitsArgs = {
  relativePath: Scalars['String']['input'];
  params: Sponsor_BenefitsMutation;
};


export type MutationCreateSponsor_BenefitsArgs = {
  relativePath: Scalars['String']['input'];
  params: Sponsor_BenefitsMutation;
};


export type MutationUpdateGet_InvolvedArgs = {
  relativePath: Scalars['String']['input'];
  params: Get_InvolvedMutation;
};


export type MutationCreateGet_InvolvedArgs = {
  relativePath: Scalars['String']['input'];
  params: Get_InvolvedMutation;
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateGrantsArgs = {
  relativePath: Scalars['String']['input'];
  params: GrantsMutation;
};


export type MutationCreateGrantsArgs = {
  relativePath: Scalars['String']['input'];
  params: GrantsMutation;
};

export type DocumentUpdateMutation = {
  sponsors?: InputMaybe<SponsorsMutation>;
  tournament?: InputMaybe<TournamentMutation>;
  contacts?: InputMaybe<ContactsMutation>;
  sponsor_benefits?: InputMaybe<Sponsor_BenefitsMutation>;
  get_involved?: InputMaybe<Get_InvolvedMutation>;
  site?: InputMaybe<SiteMutation>;
  about?: InputMaybe<AboutMutation>;
  grants?: InputMaybe<GrantsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  sponsors?: InputMaybe<SponsorsMutation>;
  tournament?: InputMaybe<TournamentMutation>;
  contacts?: InputMaybe<ContactsMutation>;
  sponsor_benefits?: InputMaybe<Sponsor_BenefitsMutation>;
  get_involved?: InputMaybe<Get_InvolvedMutation>;
  site?: InputMaybe<SiteMutation>;
  about?: InputMaybe<AboutMutation>;
  grants?: InputMaybe<GrantsMutation>;
};

export type SponsorsItemsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  enabled?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SponsorsMutation = {
  items?: InputMaybe<Array<InputMaybe<SponsorsItemsMutation>>>;
};

export type TournamentMutation = {
  edition?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  price_player?: InputMaybe<Scalars['Float']['input']>;
  price_foursome?: InputMaybe<Scalars['Float']['input']>;
  holes?: InputMaybe<Scalars['Float']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  format_label?: InputMaybe<Scalars['String']['input']>;
  inclusions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  add_ons?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  auction_description?: InputMaybe<Scalars['String']['input']>;
  section_headline?: InputMaybe<Scalars['String']['input']>;
  section_intro?: InputMaybe<Scalars['String']['input']>;
  course_description?: InputMaybe<Scalars['String']['input']>;
  register_headline?: InputMaybe<Scalars['String']['input']>;
  register_intro?: InputMaybe<Scalars['String']['input']>;
  arrive_by?: InputMaybe<Scalars['String']['input']>;
};

export type ContactsPlayersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type ContactsSponsorshipMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type ContactsMutation = {
  players?: InputMaybe<ContactsPlayersMutation>;
  sponsorship?: InputMaybe<Array<InputMaybe<ContactsSponsorshipMutation>>>;
};

export type Sponsor_BenefitsMutation = {
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Get_InvolvedItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link_label?: InputMaybe<Scalars['String']['input']>;
  form?: InputMaybe<Scalars['String']['input']>;
  form_title?: InputMaybe<Scalars['String']['input']>;
  coming_soon?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Get_InvolvedMutation = {
  items?: InputMaybe<Array<InputMaybe<Get_InvolvedItemsMutation>>>;
};

export type SiteSocialMutation = {
  facebook?: InputMaybe<Scalars['String']['input']>;
};

export type SiteHero_MissionMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  headline_line1?: InputMaybe<Scalars['String']['input']>;
  headline_line2?: InputMaybe<Scalars['String']['input']>;
  headline_accent?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDonateMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSponsor_CtaMutation = {
  headline_line1?: InputMaybe<Scalars['String']['input']>;
  headline_line2?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  copyright?: InputMaybe<Scalars['String']['input']>;
  social?: InputMaybe<SiteSocialMutation>;
  hero_mission?: InputMaybe<SiteHero_MissionMutation>;
  donate?: InputMaybe<SiteDonateMutation>;
  sponsor_cta?: InputMaybe<SiteSponsor_CtaMutation>;
};

export type AboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GrantsMutation = {
  audience?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  cta_label?: InputMaybe<Scalars['String']['input']>;
  form?: InputMaybe<Scalars['String']['input']>;
  theme?: InputMaybe<Scalars['String']['input']>;
};

export type SponsorsPartsFragment = { __typename: 'Sponsors', items?: Array<{ __typename: 'SponsorsItems', name: string, logo: string, alt: string, enabled?: boolean | null } | null> | null };

export type TournamentPartsFragment = { __typename: 'Tournament', edition: string, date: string, time: string, venue: string, address: string, price_player: number, price_foursome: number, holes: number, format: string, format_label: string, inclusions?: Array<string | null> | null, add_ons?: Array<string | null> | null, auction_description?: string | null, section_headline: string, section_intro?: string | null, course_description?: string | null, register_headline: string, register_intro?: string | null, arrive_by: string };

export type ContactsPartsFragment = { __typename: 'Contacts', players?: { __typename: 'ContactsPlayers', name: string, email: string } | null, sponsorship?: Array<{ __typename: 'ContactsSponsorship', name: string, email: string } | null> | null };

export type Sponsor_BenefitsPartsFragment = { __typename: 'Sponsor_benefits', items?: Array<string | null> | null };

export type Get_InvolvedPartsFragment = { __typename: 'Get_involved', items?: Array<{ __typename: 'Get_involvedItems', title: string, description?: string | null, link_label?: string | null, form?: string | null, form_title?: string | null, coming_soon?: boolean | null } | null> | null };

export type SitePartsFragment = { __typename: 'Site', copyright: string, social?: { __typename: 'SiteSocial', facebook?: string | null } | null, hero_mission?: { __typename: 'SiteHero_mission', badge?: string | null, headline_line1?: string | null, headline_line2?: string | null, headline_accent?: string | null, body?: string | null } | null, donate?: { __typename: 'SiteDonate', headline?: string | null, body?: string | null } | null, sponsor_cta?: { __typename: 'SiteSponsor_cta', headline_line1?: string | null, headline_line2?: string | null, intro?: string | null } | null };

export type AboutPartsFragment = { __typename: 'About', title: string, body?: any | null };

export type GrantsPartsFragment = { __typename: 'Grants', audience: string, title: string, body?: any | null, cta_label: string, form: string, theme?: string | null };

export type SponsorsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SponsorsQuery = { __typename?: 'Query', sponsors: { __typename: 'Sponsors', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'SponsorsItems', name: string, logo: string, alt: string, enabled?: boolean | null } | null> | null } };

export type SponsorsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SponsorsFilter>;
}>;


export type SponsorsConnectionQuery = { __typename?: 'Query', sponsorsConnection: { __typename?: 'SponsorsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SponsorsConnectionEdges', cursor: string, node?: { __typename: 'Sponsors', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'SponsorsItems', name: string, logo: string, alt: string, enabled?: boolean | null } | null> | null } | null } | null> | null } };

export type TournamentQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TournamentQuery = { __typename?: 'Query', tournament: { __typename: 'Tournament', id: string, edition: string, date: string, time: string, venue: string, address: string, price_player: number, price_foursome: number, holes: number, format: string, format_label: string, inclusions?: Array<string | null> | null, add_ons?: Array<string | null> | null, auction_description?: string | null, section_headline: string, section_intro?: string | null, course_description?: string | null, register_headline: string, register_intro?: string | null, arrive_by: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TournamentConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TournamentFilter>;
}>;


export type TournamentConnectionQuery = { __typename?: 'Query', tournamentConnection: { __typename?: 'TournamentConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TournamentConnectionEdges', cursor: string, node?: { __typename: 'Tournament', id: string, edition: string, date: string, time: string, venue: string, address: string, price_player: number, price_foursome: number, holes: number, format: string, format_label: string, inclusions?: Array<string | null> | null, add_ons?: Array<string | null> | null, auction_description?: string | null, section_headline: string, section_intro?: string | null, course_description?: string | null, register_headline: string, register_intro?: string | null, arrive_by: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactsQuery = { __typename?: 'Query', contacts: { __typename: 'Contacts', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, players?: { __typename: 'ContactsPlayers', name: string, email: string } | null, sponsorship?: Array<{ __typename: 'ContactsSponsorship', name: string, email: string } | null> | null } };

export type ContactsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactsFilter>;
}>;


export type ContactsConnectionQuery = { __typename?: 'Query', contactsConnection: { __typename?: 'ContactsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactsConnectionEdges', cursor: string, node?: { __typename: 'Contacts', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, players?: { __typename: 'ContactsPlayers', name: string, email: string } | null, sponsorship?: Array<{ __typename: 'ContactsSponsorship', name: string, email: string } | null> | null } | null } | null> | null } };

export type Sponsor_BenefitsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Sponsor_BenefitsQuery = { __typename?: 'Query', sponsor_benefits: { __typename: 'Sponsor_benefits', id: string, items?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Sponsor_BenefitsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Sponsor_BenefitsFilter>;
}>;


export type Sponsor_BenefitsConnectionQuery = { __typename?: 'Query', sponsor_benefitsConnection: { __typename?: 'Sponsor_benefitsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Sponsor_benefitsConnectionEdges', cursor: string, node?: { __typename: 'Sponsor_benefits', id: string, items?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Get_InvolvedQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Get_InvolvedQuery = { __typename?: 'Query', get_involved: { __typename: 'Get_involved', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'Get_involvedItems', title: string, description?: string | null, link_label?: string | null, form?: string | null, form_title?: string | null, coming_soon?: boolean | null } | null> | null } };

export type Get_InvolvedConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Get_InvolvedFilter>;
}>;


export type Get_InvolvedConnectionQuery = { __typename?: 'Query', get_involvedConnection: { __typename?: 'Get_involvedConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Get_involvedConnectionEdges', cursor: string, node?: { __typename: 'Get_involved', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'Get_involvedItems', title: string, description?: string | null, link_label?: string | null, form?: string | null, form_title?: string | null, coming_soon?: boolean | null } | null> | null } | null } | null> | null } };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, copyright: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteSocial', facebook?: string | null } | null, hero_mission?: { __typename: 'SiteHero_mission', badge?: string | null, headline_line1?: string | null, headline_line2?: string | null, headline_accent?: string | null, body?: string | null } | null, donate?: { __typename: 'SiteDonate', headline?: string | null, body?: string | null } | null, sponsor_cta?: { __typename: 'SiteSponsor_cta', headline_line1?: string | null, headline_line2?: string | null, intro?: string | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, copyright: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteSocial', facebook?: string | null } | null, hero_mission?: { __typename: 'SiteHero_mission', badge?: string | null, headline_line1?: string | null, headline_line2?: string | null, headline_accent?: string | null, body?: string | null } | null, donate?: { __typename: 'SiteDonate', headline?: string | null, body?: string | null } | null, sponsor_cta?: { __typename: 'SiteSponsor_cta', headline_line1?: string | null, headline_line2?: string | null, intro?: string | null } | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GrantsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GrantsQuery = { __typename?: 'Query', grants: { __typename: 'Grants', id: string, audience: string, title: string, body?: any | null, cta_label: string, form: string, theme?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GrantsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GrantsFilter>;
}>;


export type GrantsConnectionQuery = { __typename?: 'Query', grantsConnection: { __typename?: 'GrantsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GrantsConnectionEdges', cursor: string, node?: { __typename: 'Grants', id: string, audience: string, title: string, body?: any | null, cta_label: string, form: string, theme?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SponsorsPartsFragmentDoc = gql`
    fragment SponsorsParts on Sponsors {
  __typename
  items {
    __typename
    name
    logo
    alt
    enabled
  }
}
    `;
export const TournamentPartsFragmentDoc = gql`
    fragment TournamentParts on Tournament {
  __typename
  edition
  date
  time
  venue
  address
  price_player
  price_foursome
  holes
  format
  format_label
  inclusions
  add_ons
  auction_description
  section_headline
  section_intro
  course_description
  register_headline
  register_intro
  arrive_by
}
    `;
export const ContactsPartsFragmentDoc = gql`
    fragment ContactsParts on Contacts {
  __typename
  players {
    __typename
    name
    email
  }
  sponsorship {
    __typename
    name
    email
  }
}
    `;
export const Sponsor_BenefitsPartsFragmentDoc = gql`
    fragment Sponsor_benefitsParts on Sponsor_benefits {
  __typename
  items
}
    `;
export const Get_InvolvedPartsFragmentDoc = gql`
    fragment Get_involvedParts on Get_involved {
  __typename
  items {
    __typename
    title
    description
    link_label
    form
    form_title
    coming_soon
  }
}
    `;
export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  copyright
  social {
    __typename
    facebook
  }
  hero_mission {
    __typename
    badge
    headline_line1
    headline_line2
    headline_accent
    body
  }
  donate {
    __typename
    headline
    body
  }
  sponsor_cta {
    __typename
    headline_line1
    headline_line2
    intro
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  title
  body
}
    `;
export const GrantsPartsFragmentDoc = gql`
    fragment GrantsParts on Grants {
  __typename
  audience
  title
  body
  cta_label
  form
  theme
}
    `;
export const SponsorsDocument = gql`
    query sponsors($relativePath: String!) {
  sponsors(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SponsorsParts
  }
}
    ${SponsorsPartsFragmentDoc}`;
export const SponsorsConnectionDocument = gql`
    query sponsorsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SponsorsFilter) {
  sponsorsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SponsorsParts
      }
    }
  }
}
    ${SponsorsPartsFragmentDoc}`;
export const TournamentDocument = gql`
    query tournament($relativePath: String!) {
  tournament(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TournamentParts
  }
}
    ${TournamentPartsFragmentDoc}`;
export const TournamentConnectionDocument = gql`
    query tournamentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TournamentFilter) {
  tournamentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TournamentParts
      }
    }
  }
}
    ${TournamentPartsFragmentDoc}`;
export const ContactsDocument = gql`
    query contacts($relativePath: String!) {
  contacts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactsParts
  }
}
    ${ContactsPartsFragmentDoc}`;
export const ContactsConnectionDocument = gql`
    query contactsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactsFilter) {
  contactsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactsParts
      }
    }
  }
}
    ${ContactsPartsFragmentDoc}`;
export const Sponsor_BenefitsDocument = gql`
    query sponsor_benefits($relativePath: String!) {
  sponsor_benefits(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Sponsor_benefitsParts
  }
}
    ${Sponsor_BenefitsPartsFragmentDoc}`;
export const Sponsor_BenefitsConnectionDocument = gql`
    query sponsor_benefitsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Sponsor_benefitsFilter) {
  sponsor_benefitsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Sponsor_benefitsParts
      }
    }
  }
}
    ${Sponsor_BenefitsPartsFragmentDoc}`;
export const Get_InvolvedDocument = gql`
    query get_involved($relativePath: String!) {
  get_involved(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Get_involvedParts
  }
}
    ${Get_InvolvedPartsFragmentDoc}`;
export const Get_InvolvedConnectionDocument = gql`
    query get_involvedConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Get_involvedFilter) {
  get_involvedConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Get_involvedParts
      }
    }
  }
}
    ${Get_InvolvedPartsFragmentDoc}`;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const GrantsDocument = gql`
    query grants($relativePath: String!) {
  grants(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GrantsParts
  }
}
    ${GrantsPartsFragmentDoc}`;
export const GrantsConnectionDocument = gql`
    query grantsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GrantsFilter) {
  grantsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GrantsParts
      }
    }
  }
}
    ${GrantsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      sponsors(variables: SponsorsQueryVariables, options?: C): Promise<{data: SponsorsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorsQueryVariables, query: string}> {
        return requester<{data: SponsorsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorsQueryVariables, query: string}, SponsorsQueryVariables>(SponsorsDocument, variables, options);
      },
    sponsorsConnection(variables?: SponsorsConnectionQueryVariables, options?: C): Promise<{data: SponsorsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorsConnectionQueryVariables, query: string}> {
        return requester<{data: SponsorsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorsConnectionQueryVariables, query: string}, SponsorsConnectionQueryVariables>(SponsorsConnectionDocument, variables, options);
      },
    tournament(variables: TournamentQueryVariables, options?: C): Promise<{data: TournamentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TournamentQueryVariables, query: string}> {
        return requester<{data: TournamentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TournamentQueryVariables, query: string}, TournamentQueryVariables>(TournamentDocument, variables, options);
      },
    tournamentConnection(variables?: TournamentConnectionQueryVariables, options?: C): Promise<{data: TournamentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TournamentConnectionQueryVariables, query: string}> {
        return requester<{data: TournamentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TournamentConnectionQueryVariables, query: string}, TournamentConnectionQueryVariables>(TournamentConnectionDocument, variables, options);
      },
    contacts(variables: ContactsQueryVariables, options?: C): Promise<{data: ContactsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsQueryVariables, query: string}> {
        return requester<{data: ContactsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsQueryVariables, query: string}, ContactsQueryVariables>(ContactsDocument, variables, options);
      },
    contactsConnection(variables?: ContactsConnectionQueryVariables, options?: C): Promise<{data: ContactsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsConnectionQueryVariables, query: string}> {
        return requester<{data: ContactsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsConnectionQueryVariables, query: string}, ContactsConnectionQueryVariables>(ContactsConnectionDocument, variables, options);
      },
    sponsor_benefits(variables: Sponsor_BenefitsQueryVariables, options?: C): Promise<{data: Sponsor_BenefitsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Sponsor_BenefitsQueryVariables, query: string}> {
        return requester<{data: Sponsor_BenefitsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Sponsor_BenefitsQueryVariables, query: string}, Sponsor_BenefitsQueryVariables>(Sponsor_BenefitsDocument, variables, options);
      },
    sponsor_benefitsConnection(variables?: Sponsor_BenefitsConnectionQueryVariables, options?: C): Promise<{data: Sponsor_BenefitsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Sponsor_BenefitsConnectionQueryVariables, query: string}> {
        return requester<{data: Sponsor_BenefitsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Sponsor_BenefitsConnectionQueryVariables, query: string}, Sponsor_BenefitsConnectionQueryVariables>(Sponsor_BenefitsConnectionDocument, variables, options);
      },
    get_involved(variables: Get_InvolvedQueryVariables, options?: C): Promise<{data: Get_InvolvedQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Get_InvolvedQueryVariables, query: string}> {
        return requester<{data: Get_InvolvedQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Get_InvolvedQueryVariables, query: string}, Get_InvolvedQueryVariables>(Get_InvolvedDocument, variables, options);
      },
    get_involvedConnection(variables?: Get_InvolvedConnectionQueryVariables, options?: C): Promise<{data: Get_InvolvedConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Get_InvolvedConnectionQueryVariables, query: string}> {
        return requester<{data: Get_InvolvedConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Get_InvolvedConnectionQueryVariables, query: string}, Get_InvolvedConnectionQueryVariables>(Get_InvolvedConnectionDocument, variables, options);
      },
    site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    grants(variables: GrantsQueryVariables, options?: C): Promise<{data: GrantsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrantsQueryVariables, query: string}> {
        return requester<{data: GrantsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrantsQueryVariables, query: string}, GrantsQueryVariables>(GrantsDocument, variables, options);
      },
    grantsConnection(variables?: GrantsConnectionQueryVariables, options?: C): Promise<{data: GrantsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrantsConnectionQueryVariables, query: string}> {
        return requester<{data: GrantsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrantsConnectionQueryVariables, query: string}, GrantsConnectionQueryVariables>(GrantsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  